on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: build/dz1
        
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: build && test
        
  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: coverage
        run: build && test && coverage
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/report/index.html
