on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install libgtest-dev
    - run: mkdir build && cd build && cmake .. && make
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: build/dz1
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libgtest-dev
      - run: mkdir build && cd build && cmake .. && make
      - run: ./build/tests/dz1_test
    
  coverage:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libgtest-dev && mkdir build && cd build && cmake .. && make
      - run: ./build/tests/dz1_test && sudo apt install lcov
      - run: lcov -t "build/tests/dz1_test" -o coverage.info -c -d build/storage_device/ && genhtml -o report coverage.info
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/report/index.html
